# Generated by Django 5.1.15 on 2026-07-06 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('biblioteca', '0001_initial'),
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiladminbiblioteca',
            name='vinculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_biblioteca', to='escolas.vinculo'),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='biblioteca.turma'),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='vinculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aluno', to='escolas.vinculo'),
        ),
        migrations.AddField(
            model_name='perfilprofessor',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='professores', to='biblioteca.turma'),
        ),
        migrations.AddField(
            model_name='perfilprofessor',
            name='vinculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_professor', to='escolas.vinculo'),
        ),
        migrations.AlterUniqueTogether(
            name='perfiladminbiblioteca',
            unique_together={('vinculo', 'registro_funcional')},
        ),
        migrations.AlterUniqueTogether(
            name='perfilaluno',
            unique_together={('vinculo', 'matricula')},
        ),
        migrations.AlterUniqueTogether(
            name='perfilprofessor',
            unique_together={('vinculo', 'matricula_funcional')},
        ),
    ]
