# Generated by Django 5.1.15 on 2026-07-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_perfiladminbiblioteca_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiladminbiblioteca',
            name='registro_funcional',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilaluno',
            name='matricula',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilprofessor',
            name='matricula_funcional',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
