# Generated by Django 5.1.15 on 2026-07-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
