# Generated by Django 5.1.15 on 2026-07-06 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escolas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tombamento', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('emprestado', 'Emprestado'), ('reservado', 'Reservado'), ('danificado', 'Danificado'), ('perdido', 'Perdido')], default='disponivel', max_length=20)),
                ('condicao', models.CharField(blank=True, max_length=100)),
                ('adquirido_em', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.IntegerField(null=True)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='escolas.escola')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nacionalidade', models.CharField(blank=True, max_length=100)),
                ('biografia', models.TextField(blank=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores', to='escolas.escola')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_emprestimo_aluno', models.IntegerField(default=14)),
                ('prazo_emprestimo_professor', models.IntegerField(default=30)),
                ('prazo_emprestimo_turma', models.IntegerField(default=7)),
                ('max_renovacoes', models.IntegerField(default=2)),
                ('max_livros_aluno', models.IntegerField(default=3)),
                ('max_livros_professor', models.IntegerField(default=10)),
                ('dias_lembrete_vencimento', models.IntegerField(default=3)),
                ('max_dias_notificacao_atraso', models.IntegerField(default=30)),
                ('escola', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to='escolas.escola')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='EmprestimoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(auto_now_add=True)),
                ('data_prevista_devolucao', models.DateField()),
                ('data_real_devolucao', models.DateField(blank=True, null=True)),
                ('devolvido', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_turma', to='escolas.escola')),
                ('professor_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_turma', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_turma_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generos', to='escolas.escola')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('escola', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('editora', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('ano_publicacao', models.IntegerField(blank=True, null=True)),
                ('total_exemplares', models.IntegerField(default=1)),
                ('exemplares_disponiveis', models.IntegerField(default=1)),
                ('num_paginas', models.IntegerField(blank=True, null=True)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
                ('sinopse', models.TextField(blank=True)),
                ('localizacao_prateleira', models.CharField(blank=True, max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autores', models.ManyToManyField(blank=True, related_name='livros', to='biblioteca.autor')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='escolas.escola')),
                ('generos', models.ManyToManyField(blank=True, related_name='livros', to='biblioteca.genero')),
            ],
            options={
                'ordering': ['titulo'],
                'unique_together': {('escola', 'isbn')},
            },
        ),
        migrations.CreateModel(
            name='ItemEmprestimoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devolvido', models.BooleanField(default=False)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('emprestimo_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='biblioteca.emprestimoturma')),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.exemplar')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.livro')),
            ],
        ),
        migrations.AddField(
            model_name='exemplar',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplares', to='biblioteca.livro'),
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(auto_now_add=True)),
                ('data_prevista_devolucao', models.DateField()),
                ('data_real_devolucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('atrasado', 'Atrasado'), ('devolvido', 'Devolvido')], default='ativo', max_length=20)),
                ('renovacoes_realizadas', models.IntegerField(default=0)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='escolas.escola')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_registrados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to=settings.AUTH_USER_MODEL)),
                ('exemplar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='biblioteca.exemplar')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='biblioteca.livro')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Renovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_renovacao', models.DateTimeField(auto_now_add=True)),
                ('nova_data_devolucao', models.DateField()),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovacoes', to='biblioteca.emprestimo')),
                ('renovado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('ano_letivo', models.IntegerField()),
                ('nivel', models.CharField(choices=[('fund1', 'Fundamental I'), ('fund2', 'Fundamental II'), ('medio', 'Ensino Médio')], max_length=10)),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral')], max_length=10)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='escolas.escola')),
            ],
            options={
                'ordering': ['ano_letivo', 'codigo'],
                'unique_together': {('escola', 'codigo', 'ano_letivo')},
            },
        ),
        migrations.AddField(
            model_name='emprestimoturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_turma', to='biblioteca.turma'),
        ),
    ]
