# Generated by Django 5.1.15 on 2026-07-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_emprestimo_concluido_emprestimo_concluido_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='exigir_cpf_admin_biblioteca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='exigir_cpf_aluno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='exigir_cpf_professor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='exigir_data_nascimento_aluno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='exigir_responsavel_aluno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='exigir_telefone_admin_biblioteca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='exigir_telefone_aluno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='exigir_telefone_professor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='metodo_recuperacao_senha',
            field=models.CharField(choices=[('admin', 'Reset feito por um administrador'), ('email', 'E-mail (em breve)'), ('sms', 'SMS (em breve)')], default='admin', max_length=10),
        ),
    ]
