# Generated by Django 5.1.15 on 2026-07-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_configuracao_exigir_cpf_admin_biblioteca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='exigir_matricula_aluno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='exigir_matricula_professor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='exigir_registro_funcional_admin_biblioteca',
            field=models.BooleanField(default=False),
        ),
    ]
